export O2DPG_ROOT=/data/smrozins/alice/O2DPG 
export CURRENTDIR=`pwd`

WORKFLOWFILE="workflow.json" 

# Resources
CPU_LIMIT=64
MEM_LIMIT=200000000
NBATCHES=20

NWORKERS=${NWORKERS:-16}
MODULES="--skipModules ZDC"

SIMENGINE=${SIMENGINE:-TGeant4}
NSIGEVENTS=${NSIGEVENTS:-100}
NTIMEFRAMES=${NTIMEFRAMES:-5}
INTRATE=${INTRATE:-500000}
SYSTEM=${SYSTEM:-pp}
ENERGY=${ENERGY:-13600}