export O2DPG_ROOT=/data/smrozins/alice/O2DPG
export CURRENTDIR=`pwd`

WORKFLOWFILE="workflow.json"

# Resources
CPU_LIMIT=16
MEM_LIMIT=200000000
NBATCHES=20

# Workflow knobs
NWORKERS=${NWORKERS:-16}

MODULES="--skipModules ZDC"

SIMENGINE=${SIMENGINE:-TGeant4}

NSIGEVENTS=${NSIGEVENTS:-30}
NTIMEFRAMES=${NTIMEFRAMES:-3}

INTRATE=${INTRATE:-30000}

SYSTEM=${SYSTEM:-PbPb}
ENERGY=${ENERGY:-5036}
